name: Build

on: [push, pull_request]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt-get update
      - run: sudo apt-get install lazarus
      - run: lazbuild --version
      - uses: actions/checkout@v2
      - run: make
      - uses: actions/upload-artifact@v1
        with:
          name: linux
          path: 'SmartSet FSEdge'

  build-windows:
    runs-on: windows-latest
    steps:
      -
        name: install lazarus
        uses: crazy-max/ghaction-chocolatey@v1
        with:
          args: install lazarus make
      # https://github.community/t5/GitHub-Actions/Append-PATH-on-Windows/td-p/31120
      - run: echo "##[add-path]C:\lazarus"
      - run: lazbuild --version
      - uses: actions/checkout@v2
      -
        name: remove checked-in artifact
        run: Remove-Item -Recurse Components/richmemo/lib/x86_64-win64
      - run: make
      - uses: actions/upload-artifact@v1
        with:
          name: windows
          path: 'SmartSet FSEdge'